version: '2'
services:
  # DBサーバ
  db01:
    image: mariadb:10.1
    ports:
      - "3306:3306"
    volumes:
      # DBデータを永続化
      - ./docker/mariadb/data:/var/lib/mysql
      # 設定ファイルをマウント
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gigantic

  # Webサーバ
  web01:
    build: ./docker/httpd
    ports:
      - "80:80"
    links:
      - "db01:db01"
    volumes:
      # ソース一式をドキュメントルートに配置
      - ./:/var/www/GiganticRanking
      # apacheのログファイルをマウント
      - ./docker/logs:/var/log/httpd
      # apacheの設定ファイルをマウント
      - ./docker/httpd/00_virtualhost.conf:/etc/httpd/conf.d/00_virtualhost.conf
    privileged: true
